---
- name: create bastion host instance
  os_server:
    name: bastion-{{env}}
    state: present
    cloud: "{{ cloud_name }}"
    availability_zone: "{{ zone }}"
    image: "{{ default_os_img }}"
    key_name: "{{ user_key.name }}"
    timeout: "{{ connection_timeout }}"
    flavor: m3.small
    network: "{{ private_net.name }}"
    interface: internal
    security_groups:
      - "{{ sg.ping }}"
      - "{{ sg.dev_ssh }}"
    floating_ip_pools: "{{ public_net }}"
    wait: yes
    userdata: |
      #cloud-config
      chpasswd:
        list: |
          ubuntu:{{ user_key.password }}
        expire: False
      packages:
        - aptitude
        - ansible
        - acl
        - curl
        - wget
        - ntp
        - ntpdate
        - build-essential
        - net-tools
        - inetutils-traceroute
        - traceroute
        - git
        - gnupg
      package_upgrade: true
  register: bastion_node

- name: add the bastion node into runtime inventory with it's external address
  add_host:
    hostname: uoa_nectar-m-{{env}}
    ansible_host: "{{bastion_node.openstack.accessIPv4}}"
    groups:
      - bastion
      - dynamic
    ansible_user: "ubuntu"

- name: generate local ssh config
  template:
    src: ssh_conf.j2
    dest: "{{ playbook_dir | expanduser }}/ssh_conf"

- name: setup bastion host (send directly to this host (i.e Not local openstack call))
  copy:
    src: "{{ '~' | expanduser }}/.ssh/{{ user_key.file }}"
    dest: /home/ubuntu/.ssh/
    mode: '0600'
  delegate_to: uoa_nectar-m-{{env}}

- name: update local .ssh/config so we can ssh to this host with keys. Need a /etc/hosts entry too, so tunnelling through this host works.
  blockinfile:
    dest: "{{ '~' | expanduser }}/.ssh/config"
    block: |
      Host {{bastion_node.openstack.name}} {{bastion_node.openstack.accessIPv4}}
              User ubuntu
              IdentityFile ~/.ssh/{{ user_key.file }}
              StrictHostKeyChecking no
    marker: "# {mark} Ansible managed block {{bastion_node.openstack.name}}"
    backup: no

- name: add bastion host to /etc/hosts. Needed to be able to tunnel ssh through this host.
  lineinfile:
    path: /etc/hosts
    regexp: '^.* {{bastion_node.openstack.name}}$'
    line: "{{bastion_node.openstack.accessIPv4}} {{bastion_node.openstack.name}}"
    backup: no
  become: yes

- debug:
    msg: <
      "public':'  {{bastion_node.openstack.accessIPv4}}"
      "private':' {{bastion_node.openstack.private_v4}}"
