#pip install shade
#need entry in ~/.config/openstack/clouds.yaml
# uoa_nectardev:
#   region_name: Melbourne
#   zone: Auckland
#   auth:
#     username: r.burrowes@auckland.ac.nz
#     user_domain_name: Default
#     password: xxxxxxxxxxxxxxxxxxxx
#     project_id: cc2878baccf44324b38b96a3abced091
#     project_name: uoa_nectardev
#     project_domain_name: nz
#     auth_url: https://keystone.rc.nectar.org.au:35357/v3
#
- name: Create uoa_nectar test Environment
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/test_env.yml

  roles:
    - nectar-environment
    - nectar-server-bastion
